language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - wget http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
    - sudo dpkg -i influxdb_latest_amd64.deb
    - travis_retry sudo service influxdb restart
    - composer update --ignore-platform-reqs

script: phpunit
